/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora;

/**
 *
 * @author arrivera
 */
public class Calculadora extends javax.swing.JFrame {

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
    }

     void agregarNumero(String numero){
        if(TxtResultado.getText().charAt(0) == '0' && !numero.equals(".") && !TxtResultado.getText().contains("."))
            TxtResultado.setText("");
        
        TxtResultado.setText(TxtResultado.getText() + numero);
    }
    
    void LimpiarTexto(){
        TxtResultado.setText("0");
    }
    
    void BotonAC(){
        TxtResultado.setText("0");
        numero1 = 0;
        numero2 = 0;
        resultado = 0;
        banderaResta = 0;
        banderaSuma = 0;
        banderaMultiplicacion = 0;
        banderaDivision = 0;
        operador[0] = "";
        operador[1] = "";
    }
    
    private void verificarSetearResultado(double resultado){
        try{
            String resultadoString = String.valueOf(resultado);
            String[] resultadoArray = resultadoString.split("\\.");
            if(resultadoArray[1].equals("0"))
                TxtResultado.setText(String.valueOf(resultadoArray[0]));
            else
                TxtResultado.setText(String.valueOf(resultado));
        }catch(Exception e){
            TxtResultado.setText(String.valueOf(resultado));
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TxtResultado = new javax.swing.JTextField();
        BtnPorcentaje = new javax.swing.JButton();
        BtnCambiarSigno = new javax.swing.JButton();
        BtnC = new javax.swing.JButton();
        BtnDividir = new javax.swing.JButton();
        BtnMultiplicar = new javax.swing.JButton();
        Btn9 = new javax.swing.JButton();
        Btn8 = new javax.swing.JButton();
        Btn7 = new javax.swing.JButton();
        Btn4 = new javax.swing.JButton();
        Btn5 = new javax.swing.JButton();
        Btn1 = new javax.swing.JButton();
        Btn2 = new javax.swing.JButton();
        Btn0 = new javax.swing.JButton();
        BtnPunto = new javax.swing.JButton();
        Btn3 = new javax.swing.JButton();
        Btn6 = new javax.swing.JButton();
        BtnRestar = new javax.swing.JButton();
        BtnSumar = new javax.swing.JButton();
        BtnIgual = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        setForeground(new java.awt.Color(77, 78, 83));

        TxtResultado.setEditable(false);
        TxtResultado.setBackground(new java.awt.Color(153, 153, 153));
        TxtResultado.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        TxtResultado.setForeground(new java.awt.Color(255, 255, 255));
        TxtResultado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TxtResultado.setText("0");
        TxtResultado.setToolTipText("");
        TxtResultado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtResultadoMouseClicked(evt);
            }
        });

        BtnPorcentaje.setBackground(new java.awt.Color(102, 102, 102));
        BtnPorcentaje.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnPorcentaje.setForeground(new java.awt.Color(255, 255, 255));
        BtnPorcentaje.setText("%");
        BtnPorcentaje.setName("BtnPorcentaje"); // NOI18N
        BtnPorcentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPorcentajeActionPerformed(evt);
            }
        });

        BtnCambiarSigno.setBackground(new java.awt.Color(102, 102, 102));
        BtnCambiarSigno.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnCambiarSigno.setForeground(new java.awt.Color(255, 255, 255));
        BtnCambiarSigno.setText("+/-");
        BtnCambiarSigno.setName("BtnCambiarSigno"); // NOI18N
        BtnCambiarSigno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCambiarSignoActionPerformed(evt);
            }
        });

        BtnC.setBackground(new java.awt.Color(102, 102, 102));
        BtnC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnC.setForeground(new java.awt.Color(255, 255, 255));
        BtnC.setText("C");
        BtnC.setName("BtnC"); // NOI18N
        BtnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCActionPerformed(evt);
            }
        });

        BtnDividir.setBackground(new java.awt.Color(254, 160, 9));
        BtnDividir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnDividir.setForeground(new java.awt.Color(255, 255, 255));
        BtnDividir.setText("/");
        BtnDividir.setName("BtnDividir"); // NOI18N
        BtnDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDividirActionPerformed(evt);
            }
        });

        BtnMultiplicar.setBackground(new java.awt.Color(254, 160, 9));
        BtnMultiplicar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnMultiplicar.setForeground(new java.awt.Color(255, 255, 255));
        BtnMultiplicar.setText("X");
        BtnMultiplicar.setName("BtnMultiplicar"); // NOI18N
        BtnMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMultiplicarActionPerformed(evt);
            }
        });

        Btn9.setBackground(new java.awt.Color(153, 153, 153));
        Btn9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Btn9.setForeground(new java.awt.Color(255, 255, 255));
        Btn9.setText("9");
        Btn9.setName("Btn9"); // NOI18N
        Btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn9ActionPerformed(evt);
            }
        });

        Btn8.setBackground(new java.awt.Color(153, 153, 153));
        Btn8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Btn8.setForeground(new java.awt.Color(255, 255, 255));
        Btn8.setText("8");
        Btn8.setName("Btn8"); // NOI18N
        Btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn8ActionPerformed(evt);
            }
        });

        Btn7.setBackground(new java.awt.Color(153, 153, 153));
        Btn7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Btn7.setForeground(new java.awt.Color(255, 255, 255));
        Btn7.setText("7");
        Btn7.setName("Btn7"); // NOI18N
        Btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn7ActionPerformed(evt);
            }
        });

        Btn4.setBackground(new java.awt.Color(153, 153, 153));
        Btn4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Btn4.setForeground(new java.awt.Color(255, 255, 255));
        Btn4.setText("4");
        Btn4.setName("Btn4"); // NOI18N
        Btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn4ActionPerformed(evt);
            }
        });

        Btn5.setBackground(new java.awt.Color(153, 153, 153));
        Btn5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Btn5.setForeground(new java.awt.Color(255, 255, 255));
        Btn5.setText("5");
        Btn5.setName("Btn6"); // NOI18N
        Btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn5ActionPerformed(evt);
            }
        });

        Btn1.setBackground(new java.awt.Color(153, 153, 153));
        Btn1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Btn1.setForeground(new java.awt.Color(255, 255, 255));
        Btn1.setText("1");
        Btn1.setName("Btn1"); // NOI18N
        Btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn1ActionPerformed(evt);
            }
        });

        Btn2.setBackground(new java.awt.Color(153, 153, 153));
        Btn2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Btn2.setForeground(new java.awt.Color(255, 255, 255));
        Btn2.setText("2");
        Btn2.setName("Btn2"); // NOI18N
        Btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn2ActionPerformed(evt);
            }
        });

        Btn0.setBackground(new java.awt.Color(153, 153, 153));
        Btn0.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Btn0.setForeground(new java.awt.Color(255, 255, 255));
        Btn0.setText("0");
        Btn0.setName("Btn0"); // NOI18N
        Btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn0ActionPerformed(evt);
            }
        });

        BtnPunto.setBackground(new java.awt.Color(153, 153, 153));
        BtnPunto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnPunto.setForeground(new java.awt.Color(255, 255, 255));
        BtnPunto.setText(".");
        BtnPunto.setName("BtnPunto"); // NOI18N
        BtnPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPuntoActionPerformed(evt);
            }
        });

        Btn3.setBackground(new java.awt.Color(153, 153, 153));
        Btn3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Btn3.setForeground(new java.awt.Color(255, 255, 255));
        Btn3.setText("3");
        Btn3.setName("Btn3"); // NOI18N
        Btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn3ActionPerformed(evt);
            }
        });

        Btn6.setBackground(new java.awt.Color(153, 153, 153));
        Btn6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Btn6.setForeground(new java.awt.Color(255, 255, 255));
        Btn6.setText("6");
        Btn6.setName("Txt6"); // NOI18N
        Btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn6ActionPerformed(evt);
            }
        });

        BtnRestar.setBackground(new java.awt.Color(254, 160, 9));
        BtnRestar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnRestar.setForeground(new java.awt.Color(255, 255, 255));
        BtnRestar.setText("-");
        BtnRestar.setName("BtnResta"); // NOI18N
        BtnRestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRestarActionPerformed(evt);
            }
        });

        BtnSumar.setBackground(new java.awt.Color(254, 160, 9));
        BtnSumar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnSumar.setForeground(new java.awt.Color(255, 255, 255));
        BtnSumar.setText("+");
        BtnSumar.setName("BtnSuma"); // NOI18N
        BtnSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSumarActionPerformed(evt);
            }
        });

        BtnIgual.setBackground(new java.awt.Color(254, 160, 9));
        BtnIgual.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnIgual.setForeground(new java.awt.Color(255, 255, 255));
        BtnIgual.setText("=");
        BtnIgual.setName("BtnIgual"); // NOI18N
        BtnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIgualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtResultado)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnIgual, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Btn4, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                    .addComponent(Btn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Btn2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Btn5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Btn3, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                    .addComponent(Btn6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Btn7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BtnC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Btn8, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                    .addComponent(BtnCambiarSigno, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtnPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtnSumar, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                            .addComponent(BtnRestar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnMultiplicar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnDividir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TxtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnC, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCambiarSigno, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnRestar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnSumar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    double numero1, numero2, resultado;
    int banderaResta = 0,banderaSuma = 0,banderaMultiplicacion = 0,banderaDivision = 0;
    String[] operador = new String[]{"",""};
    
    private void BtnPorcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPorcentajeActionPerformed

        numero2 = Double.parseDouble(TxtResultado.getText());
        switch(operador[0]){
            case "":
            numero1 = Double.parseDouble(TxtResultado.getText());
            verificarSetearResultado((numero1 / 100));
            operador[1] = "=";
            break;
            case "+":
            double numeroPorcentaje = numero2 / 100;
            double porcentaje = numero1 * numeroPorcentaje;
            verificarSetearResultado(numero1 + porcentaje);
            operador[1] = "=";
            break;
            case "-":
            System.out.println("Hacemos calculo");
            
            double numeroPorcentajeResta = numero2 / 100;
            double porcentajeResta = numero1 * numeroPorcentajeResta;
            verificarSetearResultado(numero1 - porcentajeResta);
            operador[1] = "=";
            break;
            case "X":
            double numeroPorcentajeMultiplicacion = numero2 / 100;
            double porcentajeMultiplicacion = numero1 * numeroPorcentajeMultiplicacion;
            verificarSetearResultado(porcentajeMultiplicacion);
            operador[1] = "=";
            break;
            case "/":
            if(numero2 == 0)
            TxtResultado.setText("Error");
            else{
                double numeroPorcentajeDivision = numero2 / 100;
                double porcentajeDivision = numero1 * numeroPorcentajeDivision;
                verificarSetearResultado(numero1 / porcentajeDivision);
                operador[1] = "=";
            }
            break;
            default:
            break;
        }

        if(operador.equals(""))
        {

        }

    }//GEN-LAST:event_BtnPorcentajeActionPerformed

    private void BtnCambiarSignoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCambiarSignoActionPerformed
        Double numero = Double.parseDouble(TxtResultado.getText());
        if(numero == 0)
            return;
        
        verificarSetearResultado(numero * -1);
    }//GEN-LAST:event_BtnCambiarSignoActionPerformed

    private void BtnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCActionPerformed
        BotonAC();
    }//GEN-LAST:event_BtnCActionPerformed

    private void BtnDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDividirActionPerformed
        if(!operador[0].equals("/") && operador[1].equals("=")){
            setearValor1("/");
            return;
        }
        
        if(!operador[0].equals("")  && !operador[0].equals("/"))
        {
            operador[0] = "/";
            return;
        }
        
        banderaDivision++;
        if(banderaDivision > 1){
            LimpiarTexto();
            return;
        }
        
        setearValor1("/");
    }//GEN-LAST:event_BtnDividirActionPerformed

    private void setearValor1(String operadorValor){
        numero1 = Double.parseDouble(TxtResultado.getText());
        operador[0] = operadorValor;
        LimpiarTexto();
    }
    
    
    private void BtnMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMultiplicarActionPerformed
        if(!operador[0].equals("X") && operador[1].equals("=")){
            setearValor1("X");
            return;
        }
        
        if(!operador[0].equals("")  && !operador[0].equals("X"))
        {
            operador[0] = "X";
            return;
        }
        
        banderaMultiplicacion++;
        if(banderaMultiplicacion > 1){
            LimpiarTexto();
            return;
        }
        
        setearValor1("X");
    }//GEN-LAST:event_BtnMultiplicarActionPerformed

    private void Btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn9ActionPerformed
        agregarNumero(evt.getActionCommand());
    }//GEN-LAST:event_Btn9ActionPerformed

    private void Btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn8ActionPerformed
        agregarNumero(evt.getActionCommand());
    }//GEN-LAST:event_Btn8ActionPerformed

    private void Btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn7ActionPerformed
        agregarNumero(evt.getActionCommand());
    }//GEN-LAST:event_Btn7ActionPerformed

    private void Btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn4ActionPerformed
        agregarNumero(evt.getActionCommand());
    }//GEN-LAST:event_Btn4ActionPerformed

    private void Btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn5ActionPerformed
        agregarNumero(evt.getActionCommand());
    }//GEN-LAST:event_Btn5ActionPerformed

    private void Btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn1ActionPerformed
        agregarNumero(evt.getActionCommand());
    }//GEN-LAST:event_Btn1ActionPerformed

    private void Btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn2ActionPerformed
        agregarNumero(evt.getActionCommand());
    }//GEN-LAST:event_Btn2ActionPerformed

    private void Btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn0ActionPerformed
        agregarNumero(evt.getActionCommand());
    }//GEN-LAST:event_Btn0ActionPerformed

    private void BtnPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPuntoActionPerformed
        if(TxtResultado.getText().contains("."))
            return;
        
        agregarNumero(evt.getActionCommand());
    }//GEN-LAST:event_BtnPuntoActionPerformed

    private void Btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn3ActionPerformed
        agregarNumero(evt.getActionCommand());
    }//GEN-LAST:event_Btn3ActionPerformed

    private void Btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn6ActionPerformed
        agregarNumero(evt.getActionCommand());
    }//GEN-LAST:event_Btn6ActionPerformed
    
    private void BtnRestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRestarActionPerformed
        if(!operador[0].equals("-") && operador[1].equals("=")){
            setearValor1("-");
            return;
        }
        
        if(!operador[0].equals("")  && !operador[0].equals("-"))
        {
            operador[0] = "-";
            return;
        }
        banderaResta++;
        if(banderaResta > 1){
            LimpiarTexto();
            return;
        }
        setearValor1("-");
    }//GEN-LAST:event_BtnRestarActionPerformed
 
    private void BtnSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSumarActionPerformed
        if(!operador[0].equals("+") && operador[1].equals("=")){
            setearValor1("+");
            return;
        }
        
        if(!operador[0].equals("")  && !operador[0].equals("+"))
        {
            operador[0] = "+";
            return;
        }
        
        banderaSuma++;
        if(banderaSuma > 1){
            LimpiarTexto();
            return;
        }
        
        setearValor1("+");

    }//GEN-LAST:event_BtnSumarActionPerformed
 
    private void BtnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIgualActionPerformed
        banderaResta = 0;
        banderaSuma = 0;
        banderaMultiplicacion = 0;
        banderaDivision = 0;
        
        System.out.println(operador[0]);
        System.out.println(TxtResultado.getText());
        numero2 = Double.parseDouble(TxtResultado.getText());
        switch(operador[0]){
            case "+":
            resultado = numero1 + numero2;
            verificarSetearResultado(resultado);
            operador[1] = "=";
            break;
            case "-":
            resultado = numero1 - numero2;
            verificarSetearResultado(resultado);
            operador[1] = "=";
            break;
            case "X":
            resultado = numero1 * numero2;
            verificarSetearResultado(resultado);
            operador[1] = "=";
            break;
            case "/":
            if(numero2 == 0)
            TxtResultado.setText("Error");
            else{
                resultado = numero1 / numero2;
                verificarSetearResultado(resultado);
                operador[1] = "=";
            }
            break;
            case "%":
            resultado = (numero1 / numero2) * 100;
            verificarSetearResultado(resultado);
            operador[1] = "=";
            break;
            default:
            break;
        }

    }//GEN-LAST:event_BtnIgualActionPerformed

    private void TxtResultadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtResultadoMouseClicked
        if (TxtResultado.getText().equals("0") || TxtResultado.getText().length() == 1) {
            TxtResultado.setText("0");
        }else{
            TxtResultado.setText(TxtResultado.getText().substring(0,TxtResultado.getText().length()-1));
        }
    }//GEN-LAST:event_TxtResultadoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn0;
    private javax.swing.JButton Btn1;
    private javax.swing.JButton Btn2;
    private javax.swing.JButton Btn3;
    private javax.swing.JButton Btn4;
    private javax.swing.JButton Btn5;
    private javax.swing.JButton Btn6;
    private javax.swing.JButton Btn7;
    private javax.swing.JButton Btn8;
    private javax.swing.JButton Btn9;
    private javax.swing.JButton BtnC;
    private javax.swing.JButton BtnCambiarSigno;
    private javax.swing.JButton BtnDividir;
    private javax.swing.JButton BtnIgual;
    private javax.swing.JButton BtnMultiplicar;
    private javax.swing.JButton BtnPorcentaje;
    private javax.swing.JButton BtnPunto;
    private javax.swing.JButton BtnRestar;
    private javax.swing.JButton BtnSumar;
    private javax.swing.JTextField TxtResultado;
    // End of variables declaration//GEN-END:variables
}
